CREATE TABLE roles (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nombre VARCHAR(20) NOT NULL,
    nivel INT NOT NULL DEFAULT 0
);

INSERT INTO roles VALUES (0, 'USUARIO', 0);
INSERT INTO roles VALUES (1, 'PROFESOR', 3);
INSERT INTO roles VALUES (2, 'DIRECCION', 5);
INSERT INTO roles VALUES (3, 'ADMINISTRADOR', 10);
